version: '3.1'

services:
  db:
    image: mysql:8.0-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: valenpark
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: