version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: valenpark
      POSTGRES_DB: valenpark
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    volumes:
      - adminer_data:/var/www/html

volumes:
  postgres_data:
  adminer_data:
