spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: reservations
          uri: lb://reservations
          predicates:
            - Path=/reservations/**
        - id: parkings
          uri: lb://parkings
          predicates:
            - Path=/parkings/**
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

server:
  port: 8085
