spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: id-users
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: id-reservations
          uri: lb://reservations
          predicates:
            - Path=/reservations/**

server:
  port: 8085
  servlet:
    context-path: /gateway
