spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
        - id: reservations
          uri: lb://reservations
          predicates:
            - Path=/reservations/**
        - id: parkings
          uri: lb://parkings
          predicates:
            - Path=/parkings/**
  auth0:
    audience: http://localhost:8085

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://dev-m52jv12hskfqnedt.us.auth0.com/

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE